<?php $pageTitle = page_title('Order '.$order['order_number']); $page = 'orders'; ?>
<div class="dashboard-head reveal"><div><a class="text-green" style="font-size:.8rem;font-weight:750" href="<?= e(url('orders')) ?>">← Back to orders</a><h1 style="margin-top:7px"><?= e($order['order_number']) ?></h1><p>Placed <?= format_date($order['created_at'],'M j, Y · g:i A') ?> · <?= status_pill($order['status']) ?></p></div><div style="display:flex;gap:8px;flex-wrap:wrap"><?php if ($order['status']==='completed'): ?><form method="post" action="<?= e(url('reorder')) ?>"><?= csrf_field() ?><input type="hidden" name="order_id" value="<?= (int)$order['id'] ?>"><button class="btn btn-light" type="submit"><?= icon('orders') ?> Reorder</button></form><?php endif; ?><?php if (in_array($order['status'],['placed','accepted'],true) && strtotime($order['cutoff_at'])>time()): ?><form method="post" action="<?= e(url('order-cancel')) ?>" data-confirm="Cancel this pickup order? Stock will be released."><?= csrf_field() ?><input type="hidden" name="order_id" value="<?= (int)$order['id'] ?>"><button class="btn btn-danger" type="submit">Cancel order</button></form><?php endif; ?></div></div>
<div class="detail-grid">
<div>
<div class="content-card card"><div class="content-head"><div><h2>Basket contents</h2><p><?= count($orderItems) ?> items · <?= money($order['subtotal_cents']/100) ?> due at pickup</p></div></div>
<?php foreach ($orderItems as $item): ?><div class="cart-row"><div class="table-product"><span class="table-thumb"><?php $image=product_image_url($item['image']); if($image): ?><img src="<?= e($image) ?>" alt="<?= e($item['product_name']) ?>"><?php else: ?>🥬<?php endif; ?></span><div><strong style="color:var(--green-950)"><?= e($item['product_name']) ?></strong><br><small class="text-muted"><?= money($item['price_cents']/100) ?> / <?= e($item['unit']) ?></small></div></div><div><small class="text-muted">Quantity</small><br><strong><?= (int)$item['quantity'] ?></strong></div><div><small class="text-muted">Line total</small><br><strong><?= money($item['line_total_cents']/100) ?></strong></div><div><?php if ($order['status']==='completed' && !$item['review_id']): ?><a class="btn btn-light btn-sm" href="<?= e(url('review-form',['item'=>$item['id']])) ?>">Review</a><?php elseif ($item['review_id']): ?><span class="pill pill-lime">Reviewed</span><?php else: ?><span class="pill pill-gray"><?= e($item['product_status']) ?></span><?php endif; ?></div></div><?php endforeach; ?>
<?php if ($order['note']): ?><div class="alert alert-info mt-3"><?= icon('message') ?><span><strong>Your note:</strong> <?= e($order['note']) ?></span></div><?php endif; ?>
</div>
<div class="content-card card mt-3"><div class="content-head"><div><h2>Order timeline</h2><p>Every status change is recorded.</p></div></div><div class="timeline"><?php foreach ($orderEvents as $event): ?><div class="timeline-item"><strong><?= e(ucfirst(str_replace('_',' ',$event['event_type']))) ?></strong><span><?= e($event['note']) ?> · <?= e($event['actor_name']) ?> · <?= format_date($event['created_at'],'M j, g:i A') ?></span></div><?php endforeach; ?></div></div>
</div>
<aside>
<div class="card order-summary"><span class="eyebrow">Pickup details</span><h2><?= e($order['stall_name']) ?></h2><p class="text-muted" style="font-size:.85rem"><?= e($order['market_address']) ?></p><div class="summary-line"><span>Date</span><strong><?= format_date($order['pickup_date'],'D, M j, Y') ?></strong></div><div class="summary-line"><span>Time</span><strong><?= e(date('g:i A',strtotime($order['start_time']))) ?> – <?= e(date('g:i A',strtotime($order['end_time']))) ?></strong></div><div class="summary-line"><span>Change cutoff</span><strong><?= format_date($order['cutoff_at'],'M j · g:i A') ?></strong></div><div class="summary-line"><span>Payment</span><strong>Pay farmer at pickup</strong></div><div class="summary-total"><span>Order total</span><strong><?= money($order['subtotal_cents']/100) ?></strong></div></div>
<div class="card card-pad mt-3"><span class="eyebrow">Pickup address</span><p class="text-muted" style="font-size:.85rem;margin:0"><?= e($order['pickup_address']) ?></p><p class="field-help">This address is stored with the order. Contact information is only shared with the farmer fulfilling your order.</p></div>
</aside>
</div>
